import { Enums } from "./enums.js";

let MENU = [
    {
        id: 1,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "MISTO QUENTE",
        price: 15.00,
        dsc: "Pão baguete, presunto e queijo",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 2,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "MISTO SALADA",
        price: 16.00,
        dsc: "Pão baguete, presunto, queijo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 3,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "CACHORRO QUENTE SIMPLES",
        price: 16.00,
        dsc: "Pão de hambúrguer, salsicha, tomate, cebola e batata-palha",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 4,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "CACHORRO QUENTE ESPECIAL",
        price: 22.00,
        dsc: "Pão de hambúrguer, salsicha, presunto, queijo, bacon, calabresa, tomate, cebola e batata-palha",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 5,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "DOGÃO ESPECIAL",
        price: 23.00,
        dsc: "Pão de hambúrguer, salsicha, presunto, queijo, bacon, ovo, calabresa, tomate, cebola, batata-palha e milho",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 6,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "HOT-DOG BURGER",
        price: 24.00,
        dsc: "Pão de hambúrguer, salsicha, presunto, queijo, bacon, calabresa, tomate, cebola, batata-palha, milho e hambúrguer",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 7,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-BURGUER",
        price: 16.00,
        dsc: "Pão de hambúrguer, hambúrguer, presunto, queijo e tomate",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 8,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-BURGUER DUPLO",
        price: 19.00,
        dsc: "Pão de hambúrguer, 2 hambúrgueres, 2 fatias de presunto, 2 fatias de queijo e tomate",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 9,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-SALADA",
        price: 17.00,
        dsc: "Pão de hambúrguer, hambúrguer, presunto, queijo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 10,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-EGG",
        price: 19.90,
        dsc: "Pão de hambúrguer, hambúrguer, presunto, queijo e ovo",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 11,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-EGG SALADA",
        price: 20.90,
        dsc: "Pão de hambúrguer, hambúrguer, presunto, queijo, ovo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 12,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-BACON",
        price: 19.90,
        dsc: "Pão de hambúrguer, hambúrguer, presunto, queijo e bacon",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 13,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-BACON SALADA",
        price: 20.90,
        dsc: "Pão de hambúrguer, hambúrguer, presunto, queijo, bacon, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 14,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-EGG BACON SALADA",
        price: 22.90,
        dsc: "Pão de hambúrguer, hambúrguer, presunto, queijo, bacon, ovo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 15,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-EGG BACON SALADA DUPLO",
        price: 25.80,
        dsc: "Pão de hambúrguer, 2 hambúrgueres, bacon, 2 ovos, 2 fatias de presunto, 2 fatias de queijo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 16,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-TUDO",
        price: 30.80,
        dsc: "Pão de hambúrguer, hambúrguer, calabresa, bacon, ovo, salsicha, batata-palha, presunto, queijo, milho e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 17,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-SABINOS",
        price: 36.80,
        dsc: "Pão de hambúrguer grande, contra-filé, filé de frango, hambúrguer, salsicha, calabresa, bacon, presunto, queijo, ovo, batata-palha, milho, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 18,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-PIRATININGA",
        price: 28.80,
        dsc: "Pão de hambúrguer grande, 2 hambúrgueres, 2 salsichas, bacon, presunto, queijo, milho, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 19,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-MIGUEL",
        price: 22.90,
        dsc: "Pão de hambúrguer, hambúrguer, bacon, calabresa, presunto, queijo e batata-palha",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 20,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "KIDS",
        price: 19.90,
        dsc: "Pão de hambúrguer, hambúrguer, queijo, cheddar e batata-palha",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 21,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-FRANGO",
        price: 22.00,
        dsc: "Pão de baguete, frango, queijo e presunto",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 22,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-FRANGO SALADA",
        price: 24.00,
        dsc: "Pão de baguete, frango, queijo, presunto, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 23,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-FRANBACON",
        price: 25.00,
        dsc: "Pão de baguete, frango, bacon, presunto e queijo",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 24,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-FRANBACON SALADA",
        price: 26.80,
        dsc: "Pão de baguete, frango, bacon, presunto, queijo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 25,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-FRANGO EGG BACON SALADA",
        price: 28.00,
        dsc: "Pão de baguete, frango, bacon, ovo, presunto, queijo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 26,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-LINGUIÇA",
        price: 21.90,
        dsc: "Pão de baguete, linguiça, presunto, queijo, tomate, alface e cebola",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 27,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-CALABRESA",
        price: 20.90,
        dsc: "Pão de hambúrguer, hambúrguer, calabresa, presunto, queijo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 28,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "AMERICANO",
        price: 26.90,
        dsc: "Pão de baguete, contra-filé, presunto, queijo, ovo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 29,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "PAULISTA",
        price: 24.90,
        dsc: "Pão baguete, contra-filé, presunto, queijo e tomate",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 30,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "CHURRASCO",
        price: 23.90,
        dsc: "Pão baguete, contra-filé e queijo",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 31,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "CONTRA FILÉ TUDO",
        price: 35.00,
        dsc: "Pão de baguete, contra-filé, hambúrguer, salsicha, calabresa, bacon, presunto, queijo, batata-palha, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 32,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "FILÉ DE FRANGO TUDO",
        price: 31.00,
        dsc: "Pão de baguete, filé de frango, hambúrguer, salsicha, calabresa, bacon, presunto, queijo, batata-palha, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 33,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-PICANHA",
        price: 24.00,
        dsc: "Pão de hambúrguer, hambúrguer de picanha, queijo, tomate e alface",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 34,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "X-MARIA",
        price: 16.00,
        dsc: "Pão de brioche, salsicha, queijo e batata-palha",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 35,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "MS.RÚCULA",
        price: 18.90,
        dsc: "Pão de baguete, bacon, mussarela, batata-palha e rúcula",
        categoria: Enums.CATEGORIAS.TRADICIONAIS,
    },
    {
        id: 36,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BURG FRANGO",
        price: 28.90,
        dsc: "Hambúrguer de frango 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 37,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "DOUBLE FRANGO",
        price: 38.90,
        dsc: "2 Hambúrguer de frango 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 38,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BURG BEEF",
        price: 30.90,
        dsc: "Hambúrguer de carne 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 39,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "DOUBLE BEEF",
        price: 40.90,
        dsc: "2 Hambúrguer de carne 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 40,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BURG PICANHA",
        price: 36.90,
        dsc: "Hambúrguer de picanha 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 41,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "DOUBLE PICANHA",
        price: 48.90,
        dsc: "2 Hambúrguer de picanha 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 42,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BURG MIX",
        price: 30.90,
        dsc: "Hambúrguer mix bovino e suíno 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 43,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "DOUBLE MIX",
        price: 38.90,
        dsc: "2 Hambúrguer mix bovino e suíno 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 44,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BURG PIG",
        price: 30.90,
        dsc: "Hambúrguer suíno 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 45,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "DOUBLE PIG",
        price: 38.90,
        dsc: "2 Hambúrguer suíno 180g, queijo prato, bacon em tiras, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 46,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "VEGETARIANO",
        price: 29.90,
        dsc: "Hambúrguer de soja 180g, queijo, alface ou rúcula, tomate, cebola roxa e molho especial",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 47,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "KIDS BEEF",
        price: 30.90,
        dsc: "Hambúrguer de carne 180g, queijo cheddar e molho especial (Acompanha porção de batata palito 150g)",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 48,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "KIDS PICANHA",
        price: 30.90,
        dsc: "Hambúrguer de picanha 180g, queijo cheddar e molho especial (Acompanha porção de batata palito 150g)",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 49,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "KIDS FRANGO",
        price: 30.90,
        dsc: "Hambúrguer de frango 180g, queijo cheddar e molho especial (Acompanha porção de batata palito 150g)",
        categoria: Enums.CATEGORIAS.ARTESANAIS,
    },
    {
        id: 50,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "KIBE COM QUEIJO (MEIA)",
        price: 30.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 51,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "KIBE COM QUEIJO (INTEIRA)",
        price: 60.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 52,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "TILÁPIA (MEIA)",
        price: 28.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 53,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "TILÁPIA (INTEIRA)",
        price: 44.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 54,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "CALABRESA ACEBOLADA (MEIA)",
        price: 41.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 55,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "CALABRESA ACEBOLADA (INTEIRA)",
        price: 60.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 56,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "CONTRA-FILÉ ACEBOLADO (MEIA)",
        price: 32.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 57,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "CONTRA-FILÉ ACEBOLADO (INTEIRA)",
        price: 48.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 58,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "FILÉ DE FRANGO ACEBOLADO (MEIA)",
        price: 28.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 59,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "FILÉ DE FRANGO ACEBOLADO (INTEIRA)",
        price: 42.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 60,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "FRANGO À PASSARINHO (MEIA)",
        price: 28.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 61,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "FRANGO À PASSARINHO (INTEIRA)",
        price: 42.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 62,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BATATA (MEIA)",
        price: 18.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 63,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BATATA (INTEIRA)",
        price: 26.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 64,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BATATA COM BACON (MEIA)",
        price: 31.00,
        dsc: "Cheddar ou Catupiry",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 65,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BATATA COM BACON (INTEIRA)",
        price: 41.00,
        dsc: "Cheddar ou Catupiry",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 66,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BATATA COM TRIPLA (MEIA)",
        price: 30.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 67,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BATATA COM TRIPLA (INTEIRA)",
        price: 49.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 68,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "POLENTA (MEIA)",
        price: 22.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 69,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "POLENTA (INTEIRA)",
        price: 34.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 70,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "ANEL DE CEBOLA (MEIA)",
        price: 27.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 71,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "ANEL DE CEBOLA (INTEIRA)",
        price: 36.00,
        dsc: "",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 72,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "PORÇÃO MIX (MEIA)",
        price: 41.00,
        dsc: "Contra-filé, filé de frango e calabresa acebolada",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 73,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "PORÇÃO MIX (INTEIRA)",
        price: 60.00,
        dsc: "Contra-filé, filé de frango e calabresa acebolada",
        categoria: Enums.CATEGORIAS.PORCOES,
    },
    {
        id: 74,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "COCA-COLA LATA",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 75,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "GUARANÁ LATA",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 76,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "FANTA LATA",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 77,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "COCA-COLA 600ML",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 78,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "COCA-COLA 1L",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 79,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "COCA-COLA 2L",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 80,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "SUCO LATA",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 81,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "SUCO NATURAL",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 82,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "SUCO COM LEITE",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 83,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "ÁGUA",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 84,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "ÁGUA COM GÁS",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 85,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "BRAHMA LATA",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 86,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "ANTÁRTICA BOA LATA",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    },
    {
        id: 87,
        img: "./img/cardapio/burguers/Gramercy-Tavern-Burger-and-Kielbasa-Kit-6.4.21-72ppi-1x1-15.jpg",
        name: "HEINEKEN LATA",
        price: 0,
        dsc: "",
        categoria: Enums.CATEGORIAS.BEBIDAS,
    }
];
